### ISSUE TITLE
Safari can´t Load Map at staging.orte.link

### ISSUE THREAD

**Issue by Jarami110d** [a-thousand-channels/ORTE-backend#193] opened 2022-01-25 15:46 UTC
After successful log-in at https://staging.orte.link on Safari... its not possible to load any Map content. 

None of the Maps are displayed. Map area shows completely Gray.

**Comment by ut** [comment] 2022-01-25 19:52
I can confirm, possibly the action cable (websockets) calls break the javascript ("Refused to connect to wss://... because it does not appear in the connect-src directive of the Content Security Policy.")

**Comment by ut** [comment] 2022-01-25 19:53
Plus: Safari has a problem with websockets, rails-style:  https://github.com/rails/rails/issues/43835

**Comment by Sefux** [comment] 2022-01-27 15:12
Fixed in #194 
@Jarami110d can you test it on safari

**Comment by Jarami110d** [comment] 2022-01-29 20:08
Yeah! Staging is working again on Safari! 👍

**Comment by ut** [comment] 2022-02-01 12:13
Yeah :)

**Closed by ut** 2022-02-01 12:13 UTC
Labels: bug
